[package]
name = "leafbuild"
version = "0.1.0"
authors = ["Dinu Blanovschi <dinu.blanovschi001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libleaf = { path = "libleaf" }
libleafcore = { path = "libleafcore" }

[workspace]
members = [
	"libleafcore",
	"libleaf",
]