[package]
name = "leafbuild"
version = "0.1.0"
authors = ["Dinu Blanovschi <dinu.blanovschi@criptext.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
	#"meson"
]

angry-errors = ["libleaf/angry-errors"]

[dependencies]
libleaf = { path = "libleaf" }
libutils = { path = "libutils" }
meson = { path = "meson", optional = true }
clap = "3.0.0-beta.1"
log = "0.4"
pretty_env_logger = "0.4"

[workspace]
members = [
	"libutils",
	"libleafcore",
	"libleaf",
	"meson",
]