[package]
name = "sbuild"
version = "0.1.0"
authors = ["Dinu Blanovschi <dinu.blanovschi001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsbuild = { path = "libsbuild" }
libsbuildcore = { path = "libsbuildcore" }

[workspace]
members = [
	"libsbuildcore",
	"libsbuild",
]