[package]
name = "leafbuild"
version = "0.1.0"
authors = ["Dinu Blanovschi <dinu.blanovschi@criptext.com>"]
edition = "2018"

build = "build.rs" # LALRPOP preprocessing

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
	#"meson"
]

c = []
cpp = []

angry-errors = []

[dependencies]
itertools = "0.9"
libutils = { path = "libutils" }
lalrpop-util = "0.19"
regex = "1"
codespan-reporting = "0.9"
term = "0.6"
unindent = "0.1"
termcolor = "1.1"
paste = "1.0"
log = "0.4"
structopt = "0.3.17"
pretty_env_logger = "0.4.0"

[build-dependencies]
lalrpop = "0.19"

[workspace]
members = [
	"libutils",
	"meson",
]