[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]

[tasks.check]
dependencies = [
    "format",
    "lint",
    "test"
]

[tasks.doc-build]
install_crate = "mdbook"
cwd = "doc"
command = "mdbook"
args = ["build"]

[tasks.doc-serve]
install_crate = "mdbook"
cwd = "doc"
command = "mdbook"
args = ["serve"]

[tasks.doc-nuke]
cwd = "doc"
command = "rm"
args = ["-rf", "book"]

[tasks.doc-push]
cwd = "doc/book"
script = [
    '''
    git init
    git remote add origin git@github.com:leafbuild/leafbuild.github.io.git
    git add -A
    git commit -S -a -m "Update docs"
    git push -f origin master
    '''
]
dependencies = [
    "doc-build"
]

[tasks.doc-build-highlighter]
cwd = "doc"
script = [
    '''
    cp ./leafbuild_highlight.js hl_clone/highlight.js/src/languages/leafbuild.js
    pushd hl_clone || exit $?
    cd highlight.js || exit $?
    node tools/build.js -n leafbuild rust bash || exit $?
    popd || exit $?
    cp hl_clone/highlight.js/build/highlight.js theme/highlight.js || exit $?
    '''
]

[tasks.setup-dev-env]
script = [
    '''
    git config core.hooksPath git/hooks
    mkdir -p doc/hl_clone
    git clone https://github.com/highlightjs/highlight.js doc/hl_clone/highlight.js
    cd doc/hl_clone/highlight.js
    npm install
    '''
]

[tasks.clean-dev-env]
script = [
    '''
    rm -rf doc/hl_clone
    '''
]

[tasks.verify-commit-message]
cwd = "git"
command = "cargo"
args = [
    "run",
    "--package", "leafbuild-git-utils",
    "--bin", "verify_commit_message",
    "--",
    # Check for files in the root directory
    "../${@}"
]
