# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
# Orchestrate or schedule a set of jobs
workflows:
  build-deploy:
    jobs:
#      - build:
#          filters:
#            branches:
#              only:
#                - staging
#                - trying
      - test:
          # run full test cycle for 'merge' or 'try'
          filters:
            branches:
              only:
                - staging
                - trying
#      - publish:
#          requires:
#            - test
#          # only publish site changes on 'merge'
#          filters:
#            branches:
#              only: staging

jobs:
  test:
    docker:
      - image: 'rust:1'
    steps:
      - run:
          name: Install cargo-make
          command: cargo install --debug cargo-make
      - checkout
      - run:
          name: Install toolchain components
          command: rustup component add rustfmt clippy
      - run:
          name: CI Flow
          command: cargo make ci-flow
#  build:
#    docker:
#      - image: 'rust:1'
#    steps:
#      - run:
#          name: Install cargo-make
#          command: cargo install --debug cargo-make
#      - checkout
#      - run:
#          name: Install toolchain components
#          command: rustup component add rustfmt clippy
#      - run:
#          name: CI Flow
#          command: cargo make ci-flow
