[book]
authors = ["Dinu Blanovschi"]
language = "en"
multilingual = false
src = "src"
title = "The Leaf Build System"

git-repository-url = "https://gitlab.com/leafbuild/leafbuild"
git-repository-icon = "fa-gitlab"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
curly-quotes = true

[output.html.fold]
enable = true
level = 1
