name: rust
on:
  push:
    branches:
      - staging
      - trying
env:
  CLICOLOR_FORCE: 1
jobs:
  rust-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - name: 'Install cargo-make'
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          use-tool-cache: true

      - name: Run CI
        if: matrix.rust != 'nightly'
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ci-flow

      - name: Run CI (Allow Failures)
        if: matrix.rust == 'nightly'
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ci-flow

  rust-fmtcheck:
    runs-on: ubuntu-latest
    needs: rust-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Run CI
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
